### ISSUE TITLE
Duplicate content-type Headers, 0.9.0-RC1

### ISSUE THREAD

**Issue by s0kil** [com-lihaoyi/requests-scala#161]
Using requests:0.9.0-RC1, setting Content-Type header results in duplicate content type headers. Confirmed 0.9.0-RC1 only, v0.8.3 does not have this issue.

```scala
// A method to generate headers for authentication
private def headers: Map[String, String] =
    val default = Map("Content-Type" -> "application/json")
    token match
        case None    => default
        case Some(t) => default + ("Authorization" -> s"Bearer $t")

val response = requests.post(
  s"$baseUrl/unlock",
  headers = headers,
  data = write(body)
)
```

![Screenshot from 2024-06-26 12-09-53](https://github.com/com-lihaoyi/requests-scala/assets/24403355/2cc11ebe-b729-44cb-9a91-8721a163e31c)

**Comment by lihaoyi** [comment]
@nafg would it be possible for you to look into this? Should be related to the new Java11 HttpClient backend

**Comment by nafg** [comment]
Or my refactor. Didn't see this before. I can look into it.

**Comment by nafg** [comment]
So I think the explanation for what changed is that previous it `foreach`ed over all the headers calling [setRequestProperty](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setRequestProperty-java.lang.String-java.lang.String-) for each one, which means _all_ headers will only end up with the last of each. But in my change, I just concatenate the headers from the various sources and add them.

This previous behavior is perhaps questionable, because the nature of headers is that it is permitted to send multiple of the same header. In practice, at least when it comes to standard request headers, this seems to never be necessary since the values can always be combined into one header. For example, you could do

   ```http
   Accept: text/html
   Accept: application/xhtml+xml
   ```

   But you can just as well do
   ```
   Accept: text/html, application/xhtml+xml
   ```


That said, if the goal is to be backwards compatible at the cost of some flexibility (while perhaps surprising to someone *trying* to set multiple `Accept`s or whatever), I can make that change.

**Comment by nafg** [comment]
Meaning, the other option would be that we should handle cases like content type specially, or headers from the request blob specially, or something like that.

**Comment by nafg** [comment]
Or, make it easier to override the content type of a RequestBlob

**Comment by lihaoyi** [comment]
@nafg as a first pass let's just de-duplicate the headers to match the behavior of 8.x. From what I can tell, other libraries have similar limitations (e.g. https://stackoverflow.com/questions/16789840/python-requests-cant-send-multiple-headers-with-same-key), and they all can work around it by taking the repeated headers as a single comma-separated string. 

Since your work so far has preserved bincompat, let's maintain that at least for 0.9.0, and we can decide if we want to overhaul the API as part of a future release

**Comment by s0kil** [comment]
@nafg @lihaoyi  Thanks!, Tested v0.9.0, works as expected.

**Comment by nafg** [comment]
Great!
